name: check on pull request

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
      # You may pin to the exact commit or the version.
      # uses: zcong1993/setup-timezone@7215c3ec086d387e4618c4b81482d06d998c90a9
        uses: zcong1993/setup-timezone@v1.1.2
        with:
        # which timezone you want to use
          timezone: Asia/Shanghai # default is UTC
      - name: Fuck you bad packet header
        run: |
          git config --global pack.windowMemory "100m"
          git config --global pack.packSizeLimit "100m"
          git config --global pack.threads "1"
          git config --global pack.deltaCacheSize "512m"
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: bash ./gradlew assembleDebug

      - name: Sign Debug APK
        if: success()
        id: sign_debug
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./HMCLPE/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: HMCL-PE_debug
          path: ${{ steps.sign_debug.outputs.signedReleaseFile }}
